extends Node

const MAX_VELOCITY := 1000.0;
const MAX_COYOTE_TIME := 0.2;

# ADJUSTABLES ==================================================================
const BASE_WALK_SPEED := 500.0;
const BASE_DASH_SPEED := 500.0;
const BASE_JUMP_STRENGTH := 400.0;

var ADJUST_WALK_SPEED := 0.0;
var ADJUST_DASH_SPEED := 0.0;
var ADJUST_JUMP_STRENGTH := 0.0;

var TOTAL_WALK_SPEED := BASE_WALK_SPEED + ADJUST_WALK_SPEED;
var TOTAL_DASH_SPEED := BASE_DASH_SPEED + ADJUST_DASH_SPEED;
var TOTAL_JUMP_VELOCITY := BASE_JUMP_STRENGTH + ADJUST_JUMP_STRENGTH;
