extends Node

const MAX_VELOCITY := 1000.0;
const MAX_COYOTE_TIME := 0.1;
const MAX_INPUT_BUFFER_TIME := 0.1;

# ADJUSTABLES ==================================================================
const BASE_WALK_SPEED := 300.0;
const BASE_DASH_SPEED := 500.0;
const BASE_DASH_TIME := 0.2;
const BASE_JUMP_TIME := 0.1;
const BASE_JUMP_VELOCITY := 400.0;
const BASE_WALL_SLIDE_SPEED := 100.0;

var ADJUST_WALK_SPEED := 0.0;
var ADJUST_DASH_SPEED := 0.0;
var ADJUST_DASH_TIME := 0.0;
var ADJUST_JUMP_TIME := 0.0;
var ADJUST_JUMP_VELOCITY := 0.0;
var ADJUST_WALL_SLIDE_SPEED := 0.0;

func GET_TOTAL_WALK_SPEED() -> float: return BASE_WALK_SPEED + ADJUST_WALK_SPEED;
func GET_TOTAL_DASH_SPEED() -> float: return BASE_DASH_SPEED + ADJUST_DASH_SPEED;
func GET_TOTAL_DASH_TIME() -> float: return BASE_DASH_TIME + ADJUST_DASH_TIME;
func GET_TOTAL_JUMP_TIME() -> float: return BASE_JUMP_TIME + ADJUST_JUMP_TIME;
func GET_TOTAL_JUMP_VELOCITY() -> float: return BASE_JUMP_VELOCITY + ADJUST_JUMP_VELOCITY;
func GET_TOTAL_WALL_SLIDE_VELOCITY() -> float: return BASE_WALL_SLIDE_SPEED + ADJUST_WALL_SLIDE_SPEED;
